### ISSUE TITLE
masters regressions tests failing in ways not consistent with current package set

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#1147]
**Description**
masters regression tests are failing all over the place.  I think the environment is busted.

https://cxc.harvard.edu/mta/ASPECT/skawatch3/2023219/log29.html

**To Reproduce**
```
jeanconn-kady> source /export/jgonzale/github-workflows/miniconda3-shiny/envs/ska3-masters-prime/bin/ska_envs.sh
jeanconn-kady> ipython
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import Chandra.Maneuver

In [2]: Chandra.Maneuver.test()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 Chandra.Maneuver.test()

AttributeError: module 'Chandra.Maneuver' has no attribute 'test'
```

The failures in the ska_testr area look like
```
/proj/sot/ska/www/ASPECT_ICXC/skare3/dashboard/tests/Chandra.Maneuver
jeanconn-kady> more test_unit.log
Traceback (most recent call last):
  File "/export/jgonzale/ska_testr/test_outputs/logs/Linux_2023-08-07T03-01-21_d341713_kady.cfa.harvard.edu/Chandra.Maneuver/test_unit.py", line 2, in <module>
    testr.testr()
  File "/export/jgonzale/github-workflows/miniconda3/envs/ska3-masters-prime/lib/python3.10/site-packages/testr/runner.py", line 36, in testr
    return test(*args, **kwargs)
  File "/export/jgonzale/github-workflows/miniconda3/envs/ska3-masters-prime/lib/python3.10/site-packages/testr/runner.py", line 158, in test
    pkg_paths = [os.path.dirname(calling_func_file)] + ['..'] * len(pkg_names)
  File "/export/jgonzale/github-workflows/miniconda3/envs/ska3-masters-prime/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Expected behavior**
Tests should run and pass.

**Comment by javierggt** [comment]
I recreated the whole conda setup in `/export/jgonzale/github-workflows/miniconda3`. Part of this update is that I went back to using the `ska3-masters` environment (there is no `ska3-masters-prime` anymore).

Tests seem ok now. We should keep an eye on updates, to make sure it updates correctly.

**Comment by jeanconn** [comment]
PS I would figure we could check the conda meta history to for the actual log of updates in the new environment, if it goes astray.
