### ISSUE TITLE
sparkles conda package will not build without SKA defined

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#116]
sparkles conda package will not build without SKA defined.

```
Ignoring indexes: https://pypi.python.org/simple
Processing /export/aca/skare3/builds/sparkles_1551797816731/work
  Running setup.py (path:/tmp/pip-rbuc01t1-build/setup.py) egg_info for package from file:///export/aca/skare3/builds/sparkles_1551797816731/work
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-rbuc01t1-build/setup.py", line 1, in <module>
        from sparkles import __version__
      File "/tmp/pip-rbuc01t1-build/sparkles/__init__.py", line 3, in <module>
        from .core import run_aca_review, ACAReviewTable
      File "/tmp/pip-rbuc01t1-build/sparkles/core.py", line 29, in <module>
        from proseco.catalog import ACATable
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/proseco/catalog.py", line 7, in <module>
        from .core import ACACatalogTable, get_kwargs_from_starcheck_text, MetaAttribute
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/proseco/core.py", line 20, in <module>
        from mica.archive.aca_dark import get_dark_cal_image
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/mica/archive/aca_dark/__init__.py", line 2, in <module>
        from .dark_cal import *
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/mica/archive/aca_dark/dark_cal.py", line 19, in <module>
        from mica.common import MICA_ARCHIVE_PATH, MissingDataError
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/mica/common.py", line 11, in <module>
        FLIGHT_MICA_ARCHIVE = os.path.join(os.environ['SKA'], 'data', 'mica', 'archive')
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'SKA'
```

**Comment by jeanconn** [comment]
I think I can just set SKA to /dev/null in the sparkes build.sh for this.  All we need is for the import of the sparkles version to work ...

**Comment by taldcroft** [comment]
Clearly have not yet mastered the fine art of setup.py vis a vis defining the package version in exactly one place but not importing the package and all its dependencies to build.  If you have ideas...

**Comment by jeanconn** [comment]
Right, I was thinking "why does it have to import *everything* to get the version" but I didn't see lightweight ways to implement a fix for this release.

**Comment by taldcroft** [comment]
OK, here is a definitive resource:
https://packaging.python.org/guides/single-sourcing-package-version/

Without changing anything else, I think the best answer for sparkles is (1).

**Comment by taldcroft** [comment]
We could put those helper funcs into `testr` to avoid repetition.  The `testr` package is at least a lighter requirement for building.
