### ISSUE TITLE
ska_builder.py incompatible with modern compiler recipes

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#391]
**Description**

It looks like the standard for modern recipes is to use jinja to define the compiler dependencies and that doesn't work with ska_builder.py.

As in, if I try to add 
```
 requirements:
     build:
       - {{ compiler(‘c’) }}
```
to the xija recipe, the ska build process doesn't get as far as calling conda build.

**To Reproduce**
With the above compiler jinja, I end up with:
```
Using temporary directory /var/folders/63/ljv0yn5x01x6xf4cymvh814m0000gn/T/tmpb4r3xs7q for cloning
- Building package xija.
  - Cloning or updating source source xija.
xija failed, continue anyway (y/n)?
n
Traceback (most recent call last):
  File "ska_builder.py", line 166, in build_list_packages
    clone_repo(pkg_name, args, src_dir)
  File "ska_builder.py", line 70, in clone_repo
    meta = yaml.safe_load(jinja2.Template(meta_text).render())
  File "/Users/jean/conda_4.8.2/envs/builder/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/jean/conda_4.8.2/envs/builder/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/jean/conda_4.8.2/envs/builder/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 18, in top-level template code
jinja2.exceptions.UndefinedError: 'compiler' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ska_builder.py", line 207, in <module>
    main()
  File "ska_builder.py", line 203, in main
    build_list_packages(pkg_names, args, src_dir, build_dir)
  File "ska_builder.py", line 176, in build_list_packages
    raise ValueError(f"{pkg_name} failed")
```

**Additional context**

I think I can just call out the compiler pieces explicitly instead of using the jinja syntactic sugar (that's what I've been doing on the Perl skare3-static recipes anyway).  I suppose I could also try to do something *else* with the template so that by the time it gets to conda build it looks like {{ compiler('c') }} again.

**Comment by taldcroft** [comment]
This should fix it:
```
macro = '{% macro compiler(arg) %}{% endmacro %}\n'
meta = yaml.safe_load(jinja2.Template(macro + meta_text).render())
```
