### ISSUE TITLE
Add mamba package

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#584]
There may be benefits to using `mamba` instead of `conda` for general package management. 

I had a quick look into what it might require to add this. All looks OK except I'm worried about that python_abi from conda forge.  I can't quite tell from https://conda-forge.org/blog/posts/2020-03-10-pypy/#python-abi-package if it is generally safe to toss in that conda-forge `python_abi`.
```
(ska3) ➜  ~ conda install --strict-channel-priority --override-channels -c $ska3conda/flight -c defaults -c conda-forge mamba
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/aldcroft/miniconda3/envs/ska3

  added / updated specs:
    - mamba


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    krb5-1.18.2                |       h75d18d8_0         1.1 MB
    libcurl-7.71.1             |       h8a08a2b_1         289 KB
    libsolv-0.7.14             |       hd174df1_4         403 KB  conda-forge
    libssh2-1.9.0              |       ha12b0ac_1         250 KB
    mamba-0.4.2                |   py38hdbb38a9_0         440 KB  conda-forge
    python_abi-3.8             |           1_cp38           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.4 MB

The following NEW packages will be INSTALLED:

  krb5               pkgs/main/osx-64::krb5-1.18.2-h75d18d8_0
  libcurl            pkgs/main/osx-64::libcurl-7.71.1-h8a08a2b_1
  libsolv            conda-forge/osx-64::libsolv-0.7.14-hd174df1_4
  libssh2            pkgs/main/osx-64::libssh2-1.9.0-ha12b0ac_1
  mamba              conda-forge/osx-64::mamba-0.4.2-py38hdbb38a9_0
  python_abi         conda-forge/osx-64::python_abi-3.8-1_cp38


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
- List PR merges

**Comment by taldcroft** [comment]
As an example of mamba being nicer, I just tried something stupid, namely upgrade astropy to 4.2 in my flight env.  With `conda` it spins for a few minutes and finally fails with no useful message. With `mamba` it gives the right answer almost immediately:
```
(ska3-mamba) ➜  ska_testr git:(master) conda install --override-channels -c $ska3conda/flight -c defaults astropy=4.2 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
/ failed

CondaError: KeyboardInterrupt

(ska3-mamba) ➜  ska_testr git:(master) mamba install --override-channels -c $ska3conda/flight -c defaults astropy=4.2

        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

aspect/ska3-conda/flight [====================] (00m:00s) No change
aspect/ska3-conda/flight [====================] (00m:00s) No change
pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change

Looking for: ['astropy=4.2']

Encountered problems while solving.
Problem: package ska3-core-2021.1-0 requires astropy 4.0.1.post1, but none of the providers can be installed
```

**Comment by taldcroft** [comment]
Well there seems to be a show-stopper, namely not being able to create an environment.
```
mamba create -n ska3-from-mamba -c $ska3conda/flight ska3-flight
...
zipp                     [>                   ] (00m:05s) Couldn't resolve host name
zlib                     [>                   ] (00m:05s) Couldn't resolve host name
zstd                     [>                   ] (00m:05s) Couldn't resolve host name

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/mamba/mamba.py", line 814, in exception_converter
        raise e
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/mamba/mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/mamba/mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/mamba/mamba.py", line 667, in do_call
        exit_code = create(args, parser)
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/mamba/mamba.py", line 568, in create
        install(args, parser, 'create')
      File "/Users/aldcroft/miniconda3/envs/ska3-mamba/lib/python3.8/site-packages/mamba/mamba.py", line 532, in install
        downloaded = transaction.prompt(PackageCacheData.first_writable().pkgs_dir, repos)
    RuntimeError: Download error (6) Couldn't resolve host name [https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight/osx-64/aca_hi_bgd-0.1.5-py38_0.tar.bz2]

`$ /Users/aldcroft/miniconda3/envs/ska3-mamba/bin/mamba create -n ska3-from-mamba -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight ska3-flight`

```

**Comment by taldcroft** [comment]
The environment I created that includes `mamba` and the `python_abi` file passes ska_testr, FWIW.

**Comment by taldcroft** [comment]
Nice -- removing meta packages does what you would expect, namely just remove that metapackage and not everything that came along with it.

**Comment by jeanconn** [comment]
I assume this could be added to ska3-core-latest now.

**Comment by taldcroft** [comment]
The problem with not being able to resolve the host is bad, though oddly if I made an environment installing only `aca_hi_bgd`, then went back to installing the entire `ska3-flight`, it apparently worked.

So I'd put this in the category of let's hold the thought for a few months while they shake out more bugs and see if mamba keeps getting traction. If I find time I can put in a bug report, though it'll be difficult since the bug involves accessing icxc which they cannot do.

**Comment by jeanconn** [comment]
I think that speaks even more to adding it to ska3-core-latest (to encourage us to have dev environments that have modern versions of it to test stuff out).

**Comment by taldcroft** [comment]
Just hoping to spend less time on Ska and more on aspect over the next few months.

**Comment by javierggt** [comment]
Added as part of PR #599
